### ISSUE TITLE
print schema tree of a single model using command line utility 

### ISSUE THREAD

**Issue by jedelman8** [CZ-NIC/yangson#19]
This may be related #12 but this isn't for validation, just viewing the schema tree.  Currently, it seems any module in the mod path is printed when using `--tree` with the command line utility.  Are there plans to limit this to a given module?  Ideally, path lets you reference a specific model (or a new parameter for that)

**Comment by llhotka** [comment]
There are no such plans because
1. Yangson always works with the entire schema as described by YANG library. The ASCII tree (`--tree` option) just shows the schema, which looks similar but in fact is something else than the tree diagrams described in [RFC 8340](https://tools.ietf.org/html/rfc8340).
2. Yangson is primarily a Python library, and I don't want to make the `yangson` utility excessively complicated.

My suggestion is to use the [pyang](https://github.com/mbj4668/pyang) tool instead:
```
pyang -f tree mymodule.yang
```
