### ISSUE TITLE
Augmented module container content inaccessible when validating Json data

### ISSUE THREAD

**Issue by Doukuest** [CZ-NIC/yangson#43]
I'm trying to validate this Json data:
`{
  "ietf-netconf-acm:nacm": {
    "enable-nacm": false
  },
  "ietf-routing:routing": {
    "control-plane-protocols": {
      "control-plane-protocol": [
        {
          "type": "rpl",
          "name": "RPL",
	  "uis-rpl:example1": 1,
          "uis-rpl:rpl": {
"example2":250
}
        }
      ]
    },
    "ribs": {
      "rib": [
      ]
    }
  }
}`
It validates (and works) with every leaf or container outside the uis-rpl:rpl container. However, whenever i try to validate content **inside** the rpl container, i get this error:
`File "/home/douglas/.local/lib/python3.5/site-packages/yangson/schemadata.py", line 288, in resolve_pname
    raise UnknownPrefix(p, mid) from None
yangson.exceptions.UnknownPrefix: prefix {'example2' is not defined in ('uis-rpl', '2020-02-27')
`
I already tried validating, for example, the objective-function container with some data, and it throws the same error (instead of "... prefix {'example2' ..." is "... prefix {'objective-function' ...").
The following image is part of the data tree. I marked the sections which fails at validating.
![imagen](https://user-images.githubusercontent.com/33143337/76042936-18566d00-5f24-11ea-8a44-21af9bae6692.png)
I'm not sure if i'm doing something wrong or it is a bug.
I can attach the models if you need them.

**Comment by llhotka** [comment]
Please provide the Python script that causes the error, and the YANG library data.

**Comment by Doukuest** [comment]
Okay.
I attached a zip file that contains all YANG models named in the YANG library, the Python script and the Json data.
[test.zip](https://github.com/CZ-NIC/yangson/files/4299022/test.zip)

**Comment by llhotka** [comment]
The problem is in `uis-ofs-hc@2020-02-27.yang` and `uis-rpl@2020-02-27.yang`: the second parameter of the XPath function `derived-from()` has to be a string enclosed in quotes, see [sec. 10.4.1](https://www.rfc-editor.org/rfc/rfc7950.html#section-10.4.1) in RFC 7950. So
```
when "derived-from(rpl:type, hc:of-hops)";
```
should be
```
when "derived-from(rpl:type, 'hc:of-hops')";
```
and similarly for
```
when "derived-from(rt:type, rpl:rpl)"
```
But this has to be caught by the XPath parser, so I need to apply a fix.

**Comment by Doukuest** [comment]
I applied those corrections.
Validating with the same Json data now throws the following error:
`yangson.exceptions.SchemaError: [/ietf-routing:routing/control-plane-protocols/control-plane-protocol/0] config member-not-allowed: uis-rpl:rpl`

**Comment by llhotka** [comment]
There are several problems:

1. In `temp.json`, the value of `type` is an identity that has to be qualified with module name, se [sec. 6.8](https://www.rfc-editor.org/rfc/rfc7951.html#section-6.8) in RFC 7951:
```
         "type": "uis-rpl:rpl",
 ```

2. In `uis-rpl@2020-02-27.yang` you have to use the XPath function `derived-from-or-self` rather than `derived-from` because the `type` value is equal to `uis-rpl:rpl`:
```
  augment "/rt:routing/rt:control-plane-protocols/"
    + "rt:control-plane-protocol"{

      when "derived-from-or-self(rt:type, 'rpl:rpl')"{
        description
          "This augment is only valid for a routing protocol instance
          of RPL.";
      }
```
3. And finally, the type of the `example1` leaf is `uint8`, so the value of 257 is out of range.

**Comment by Doukuest** [comment]
Man... you saved me. Thank you very much.
